### ISSUE TITLE
Design error while being lokated inside of brackets in Markdown

### ISSUE THREAD

**Issue by inputsh** [alexmgrant/carbon-blue-atom#1]
While I'm navigating through the brackets, any text that's in the first line has a graphical error that basically consists of two horizontal lines as shown on the screenshot below.

The problem keeps being present no matter what UI Theme is activated.

![screenshot from 2015-01-12 05 57 59](https://cloud.githubusercontent.com/assets/4890548/5699129/1918ddc8-9a20-11e4-995b-0011aabab6f3.png)

**Comment by alexmgrant** [comment]
Oh, interesting! Thanks for the heads up I'll take a look.

**Comment by alexmgrant** [comment]
Ok fixed. A bunch of stuff had been depreciated since I last looked.  
There is still an issue with the current line selected that needs to be fixed.  
Thanks from the tip, happy coding!
